version: '3.8'

services:
  # Serviço da aplicação Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radar17-app
    restart: always
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017/radar17-debate
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - radar17-network

  # Serviço do MongoDB
  mongo:
    image: mongo:4.4
    container_name: radar17-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - radar17-network
    # Descomente as linhas abaixo se precisar de autenticação no MongoDB
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=password

  # Serviço do Mongo Express (interface de administração web para MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: radar17-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      # Descomente as linhas abaixo se tiver configurado autenticação no MongoDB
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - radar17-network

networks:
  radar17-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local